---
# Define the name of the microservice
microservice: task-api

create_ddl: create-task-api-db.ddl
drop_ddl: drop-task-api-db.ddl

db_url_env: TASK_API_JDBC_URL
db_user_env: TASK_API_DB_USER
db_db_env: TASK_API_DB_PASSWORD

cpu_min: 50m
cpu_max: 1000m

memory_min: 50Mi
memory_max: 200Mi
